# Generated by Django 4.2.3 on 2023-11-12 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0001_initial'),
        ('classes', '0001_initial'),
        ('task', '0003_taskgenerator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceTestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=2)),
                ('skill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='topic.skill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('write_student_name', models.BooleanField(default=True)),
                ('skill_levels', models.ManyToManyField(related_name='student_tests', to='topic.skilllevel')),
                ('stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='classes.stage')),
                ('students', models.ManyToManyField(related_name='student_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_all', models.BooleanField(default=True)),
                ('page', models.IntegerField(default=2)),
                ('choice_test_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.choicetesttask')),
                ('generators', models.ManyToManyField(related_name='test_tasks', to='task.taskgenerator')),
                ('skill_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='topic.skilllevel')),
                ('student_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.studenttest')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('groups', models.IntegerField(default=2)),
                ('date', models.DateField()),
                ('skills', models.ManyToManyField(related_name='tests', to='topic.skill')),
                ('stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='classes.stage')),
            ],
        ),
        migrations.AddField(
            model_name='choicetesttask',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.test'),
        ),
    ]
