# Generated by Django 4.2.3 on 2023-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='group_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='group_number',
            field=models.IntegerField(default=1),
        ),
    ]
