# Generated by Django 4.2.3 on 2023-07-28 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0006_stage_your_stage_initial_password_alter_topic_stage"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="your_stage",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="your_stage",
            name="user",
        ),
        migrations.DeleteModel(
            name="Initial_Password",
        ),
        migrations.DeleteModel(
            name="Stage",
        ),
        migrations.DeleteModel(
            name="Your_Stage",
        ),
    ]
