# Generated by Django 4.2.3 on 2023-09-12 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Initial_Password',
            new_name='InitialPassword',
        ),
        migrations.RenameModel(
            old_name='Your_Stage',
            new_name='YourStage',
        ),
    ]
