# Generated by Django 4.2.3 on 2023-09-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_alter_topic_stage'),
        ('users', '0004_rename_initial_password_initialpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourstage',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='yourstage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='YourStage',
        ),
    ]
