# Generated by Django 4.2.3 on 2023-11-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('grade', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.studenttest'),
        ),
        migrations.AddField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.test'),
        ),
    ]
