# Generated by Django 4.2.3 on 2023-09-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgenerator',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topic.topic'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topic.topic'),
        ),
    ]
