# Generated by Django 4.2.3 on 2023-09-25 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('required_passes', models.IntegerField(default=1)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.stage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Chill'), ('2', 'Medium'), ('3', 'Challenge')], default=1, max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('required_passes', models.IntegerField(default=1)),
                ('example_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='task.task')),
                ('generators', models.ManyToManyField(related_name='skill_levels', to='task.taskgenerator')),
                ('skills', models.ManyToManyField(related_name='levels', to='topic.skill')),
                ('tasks', models.ManyToManyField(related_name='skill_levels', to='task.task')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
        ),
    ]
