# Generated by Django 4.2.3 on 2023-09-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='example_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.task'),
        ),
    ]
