# Generated by Django 4.2.3 on 2023-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_alter_skilllevel_example_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='required_passes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='required_passes',
            field=models.IntegerField(default=1),
        ),
    ]
