# Generated by Django 4.2.3 on 2023-07-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("topic", "0004_remove_stage_teacher_remove_your_stage_stage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.stage",
            ),
        ),
    ]
