# Generated by Django 4.2.3 on 2023-08-02 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0006_stage_your_stage_initial_password_alter_topic_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug",
        ),
    ]
