# Generated by Django 4.2.3 on 2023-09-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '__first__'),
        ('topic', '0009_alter_topic_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Chill'), ('2', 'Medium'), ('3', 'Challenge')], default=1, max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('example_task', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('generators', models.ManyToManyField(related_name='skill_levels', to='task.taskgenerator')),
                ('skills', models.ManyToManyField(related_name='levels', to='topic.skill')),
                ('tasks', models.ManyToManyField(related_name='skill_levels', to='task.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
